name: elapsed_time_element
version: 0.12.1
author: Jim Heyne <jheyne@gmail.com>
homepage: https://github.com/jheyne/elapsed_time_element
description: Dart Polymer component displaying elapsed time for a DateTime instance. For example, 1 day 2 hours 3 minutes.
dependencies:
  core_elements: ">=0.3.2 <0.4.0"
  intl: ">=0.11.9 <0.12.0"
  polymer: ">=0.15.1 <0.16.0"
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points:
    - example/app.html
